#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_ARCH="arm64"

# DOWNLOAD_BASE_URL="https://github.com/plandevida/armbian-builds-orangepizero2w/releases/download/untagged-ce03419c48d6b31d0ed9"
DOWNLOAD_BASE_URL="https://dl.armbian.com/orangepizero2w/archive"

# Image source
DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}/Armbian_24.2.6_Orangepizero2w_bookworm_current_6.6.28.img.xz.sha"
DOWNLOAD_URL_IMAGE="${DOWNLOAD_BASE_URL}/Armbian_24.2.6_Orangepizero2w_bookworm_current_6.6.28.img.xz"

# export Variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_SBC_NAME="Orange Pi Zero2W"
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC="orangepizero2w-64bit"
