#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_ARCH="arm64"

DOWNLOAD_BASE_URL="https://github.com/plandevida/armbian-builds-orangepizero2w/releases/download/20240428-1209/armbian-orangepi_zero2w_others_bookworm.img"
# DOWNLOAD_BASE_URL="https://dl.armbian.com/orangepizero2w/archive/Armbian_24.2.6_Orangepizero2w_bookworm_current_6.6.28.img"

# Image source
# DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}.xz.sha"
DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}.xz.sha256"
DOWNLOAD_URL_IMAGE="${DOWNLOAD_BASE_URL}.xz"

BASE_IMAGE_ENLARGEROOT=3000

# export Variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_SBC_NAME="Orange Pi Zero2W 1500mb"
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC="orangepizero2w-64bit"
